MINOR: Clean `Metrics.defaultRegistry` to avoid transient failures in `testSessionExpireListenerMetrics`
The failure could manifest itself if the default metrics registry had some entries from other tests:

`java.lang.AssertionError: Unexpected meter count expected:<0> but was:<3>`

I also removed an unused variable and improved the error message to include the metric name.

Author: Ismael Juma <ismael@juma.me.uk>

Reviewers: Gwen Shapira

Closes #1544 from ijuma/fix-transient-session-expire-listener-metrics-failure